name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      allowed_url:
        description: 'Allowed domain'
        required: true
        default: 'example.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Inject allowed domain into MainActivity.java
        run: |
          sed -i "s|ALLOWED_URL = \".*\"|ALLOWED_URL = \"${{ github.event.inputs.allowed_url }}\"|g" app/src/main/java/com/webview/myapplication/MainActivity.java

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidRestrictedWebView-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
